-- DEPRECATED — this file is superseded by update_aum_investor_type.sql
--
-- AUM is now stored as aum_range_id (FK to aum_ranges lookup table)
-- instead of a free-text aum column.
--
-- investor_type is now normalized into:
--   investor_types (lookup) + organization_investor_types (junction)
--
-- See update_aum_investor_type.sql for the full schema + data migration.
